apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpa
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: vpa
      version: "1.4.x"
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  values:
    updater:
      enabled: false
