apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gateway
  namespace: default
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      options:
        networking.gke.io/pre-shared-certs: wisvch-20230815
  - name: http
    protocol: HTTP
    port: 80
  addresses:
  - type: NamedAddress
    value: gce-load-balancer-ipv4
  - type: NamedAddress
    value: gce-load-balancer-ipv6
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
  namespace: default
spec:
  domains:
    - cod.wisv.ch
