apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cod
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./archive
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    fullnameOverride: cod
    ingress:
      tudelft:
        domains:
          - cod.ch.tudelft.nl
        tlsSecret: chtudelft-tls
      transip:
        domains:
          - cod.wisv.ch
        tlsSecret: wisvch-tls
    replicaCount: 1
    containerPort: 8080
    service:
      type: ClusterIP
      port: 80
    image:
      repository: ghcr.io/wisvch/cod22
      tag: 20230419-7abe110 # {"$imagepolicy": "flux-system:cod22:tag"}
      pullPolicy: IfNotPresent
      pullSecrets: {}
