apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cod
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./static-site
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    fullnameOverride: codsite
    domains:
      - cod.ch.tudelft.nl
      - cod.wisv.ch
    replicaCount: 1
    containerPort: 8080
    service:
      type: ClusterIP
      port: 80
    image:
      repository: ghcr.io/wisvch/cod22
      tag: 20250327-3bb7195 # {"$imagepolicy": "flux-system:cod22:tag"}
      pullPolicy: IfNotPresent
      pullSecrets: {}
