apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: areafiftylan-legacy
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./areafiftylan-legacy
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    tlsSecret: areafiftylan-tls
    domains:
      - areafiftylan.nl
      - area51an.nl
      - area5lan.nl
    postgres:
      database: areafiftylan-legacy
    frontend:
      replicaCount: 1
      image:
        repository: ghcr.io/areafiftylan/lancie-frontend
        tag: 20230511-66e1a5b # {"$imagepolicy": "flux-system:areafiftylan-legacy-frontend:tag"}
      resources:
        requests:
          cpu: 15m
          memory: 105M
        limits:
          cpu: 15m
          memory: 105M
    api:
      replicaCount: 1
      image:
        repository: ghcr.io/areafiftylan/lancie-api
        tag: 20220408-6737b62 # {"$imagepolicy": "flux-system:areafiftylan-legacy-api:tag"}
      resources:
        requests:
          cpu: 15m
          memory: 300M
        limits:
          memory: 450M
    admin:
      replicaCount: 1
      image:
        repository: ghcr.io/areafiftylan/lancie-admin
        tag: 20220223-41883df # {"$imagepolicy": "flux-system:areafiftylan-legacy-admin:tag"}
      resources:
        requests:
          cpu: 15m
          memory: 105M
        limits:
          cpu: 15m
          memory: 105M
  valuesFrom:
    - kind: Secret
      name: postgres-new
      valuesKey: host
      targetPath: postgres.host
    - kind: Secret
      name: postgres-new
      valuesKey: port
      targetPath: postgres.port
    - kind: Secret
      name: postgres-new
      valuesKey: username
      targetPath: postgres.username
    - kind: Secret
      name: postgres-new
      valuesKey: password
      targetPath: postgres.password
    - kind: Secret
      name: areafiftylan-legacy
      valuesKey: mollie-key
      targetPath: mollie.key
    - kind: Secret
      name: areafiftylan-legacy
      valuesKey: gmaps-key
      targetPath: gmaps.key
    - kind: Secret
      name: mail
      valuesKey: username
      targetPath: mail.username
    - kind: Secret
      name: mail
      valuesKey: password
      targetPath: mail.password
    - kind: Secret
      name: mail
      valuesKey: port
      targetPath: mail.port
    - kind: Secret
      name: mail
      valuesKey: host
      targetPath: mail.host
