apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: connect2
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./connect2
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    replicaCount: 1
    tlsSecret: wisvch-tls
    serviceAccountSecretName: connect2
    serviceAccountSecretKey: serviceAccount
    service:
      ip: 10.24.13.2
    image:
      repository: ghcr.io/wisvch/connect2
      tag: 20230604-e51c5d0 # {"$imagepolicy": "flux-system:connect2:tag"}
