apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: chipcie-website
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./static-site
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    fullnameOverride: chipcie
    domains:
      - chipcie.wisv.ch
    replicaCount: 1
    containerPort: 8080
    service:
      type: ClusterIP
      port: 80
    image:
      repository: ghcr.io/wisvch/chipcie-website
      tag: 20240403-645fc58 # {"$imagepolicy": "flux-system:chipcie-website:tag"}
      pullPolicy: IfNotPresent
      pullSecrets: {}
