apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chipcie-website
  namespace: default
  spec:
    interval: 15m
    chart:
      spec:
        chart: ./chipcie
        version: "0.1.x"
        interval: 15m
        reconcileStrategy: Revision
        sourceRef:
          kind: GitRepository
          name: wisvch
          namespace: flux-system
    values:
      replicaCount: 1
      tlsSecret: wisvch-tls
      domains:
        - chipcie.wisv.ch
      image:
        repository: ghcr.io/wisvch/chipcie-website
        tag: 20230222-f7c4c4e # {"$imagepolicy": "flux-system:chipcie:tag"}
