apiVersion: v1
kind: Service
metadata:
  name: varnish-svc
  namespace: default
  labels:
    app: varnish-proxy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: varnish-proxy
  sessionAffinity: None
  type: ClusterIP
