apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: adminer
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: adminer
      version: "0.2.x"
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: cetic
        namespace: flux-system
  values:
    ingress:
      enabled: false
    service:
      type: ClusterIP
    config:
      externalserver: "10.59.96.3"
