apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave
  values:
    adminUser:
      create: true
      username: admin
  valuesFrom:
    - kind: Secret
      name: cluster-user-auth
      valuesKey: password
      targetPath: adminUser.passwordHash
