apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: events-wisvch-redirect
  namespace: default
  labels:
    app: events
spec:
  parentRefs:
  - kind: Gateway
    namespace: gateway-infra
    name: gateway
  hostnames:
    - events.wisv.ch
  rules:
    - matches:
      - path: 
          type: PathPrefix
          value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            # Hostname seems not to work.. Therefore we serve the app on /events too.
            # TODO: fix this.
            hostname: ch.tudelft.nl
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /events
            statusCode: 301
    - matches:
        - path: 
            type: PathPrefix
            value: /events
      backendRefs: 
      - name: events
        port: 80