apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: events
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./events
      version: "0.1.x"
      interval: 5m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    replicaCount: 1
    tlsSecret: wisvch-tls
    domains:
      - wisv.ch/events
    image:
      repository: ghcr.io/wisvch/events
      tag: 20230701-80ef977 # {"$imagepolicy": "flux-system:events:tag"}
    oauth:
      issuer: https://connect.ch.tudelft.nl
      client:
        url: https://events.wisv.ch
      scope: openid, profile, email, auth
      claimName: google_groups
      groups:
        admin: beheer, vc, epa, bestuur
        beta: joepj, juliand, danys
    postgres:
      database: events
      host: 127.0.0.1
      port: 5432
      cloudSQL: true
    hibernate:
      generateDdl: true
      hb2mddl:
        auto: validate
    flyway:
      enabled: true
  valuesFrom:
    - kind: Secret
      name: postgres
      valuesKey: username
      targetPath: postgres.username
    - kind: Secret
      name: postgres
      valuesKey: password
      targetPath: postgres.password
    - kind: Secret
      name: events
      valuesKey: mollie-key
      targetPath: mollie.key
    - kind: Secret
      name: events
      valuesKey: connect-client-secret
      targetPath: oauth.client.secret
    - kind: Secret
      name: events
      valuesKey: connect-client-id
      targetPath: oauth.client.id
    - kind: Secret
      name: mail
      valuesKey: username
      targetPath: mail.username
    - kind: Secret
      name: mail
      valuesKey: password
      targetPath: mail.password
    - kind: Secret
      name: mail
      valuesKey: port
      targetPath: mail.port
    - kind: Secret
      name: mail
      valuesKey: host
      targetPath: mail.host
