apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: victoriametrics
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: victoria-metrics-single
      version: "0.9.x"
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
  values:
    server:
      retentionPeriod: "1w"
      persistentVolume:
        size: 4Gi
      statefulSet:
        enabled: false
      scrape:
        enabled: true
        extraScrapeConfigs:
          - job_name: "kube-state-metrics"
            kubernetes_sd_configs:
              - role: service
            relabel_configs:
              - action: keep
                source_labels:
                  [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
                regex: default;kube-state-metrics
              - source_labels:
                  [__meta_kubernetes_pod_annotation_prometheus_io_path]
                action: replace
                target_label: __metrics_path__
                regex: (.+)
              - source_labels:
                  [
                    __address__,
                    __meta_kubernetes_pod_annotation_prometheus_io_port,
                  ]
                action: replace
                regex: ([^:]+)(?::\d+)?;(\d+)
                replacement: $1:$2
                target_label: __address__
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - source_labels: [__meta_kubernetes_namespace]
                action: replace
                target_label: kubernetes_namespace
              - source_labels: [__meta_kubernetes_pod_name]
                action: replace
                target_label: kubernetes_pod_name
      ingress:
        enabled: false
