apiVersion: apps/v1
kind: Deployment
metadata:
  name: iap
  namespace: default
spec:
  selector:
    matchLabels:
      run: iap
  template:
    metadata:
      labels:
        run: iap
    spec:
      containers:
      - image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
        imagePullPolicy: IfNotPresent
        name: iap
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: config-default
  namespace: default
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: iap
---
apiVersion: v1
kind: Service
metadata:
  name: iap
  namespace: default
  annotations:
    cloud.google.com/backend-config: '{"default": "config-default"}'