apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: default
spec:
  selector:
    matchLabels:
      run: web
  template:
    metadata:
      labels:
        run: web
    spec:
      containers:
      - image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
        imagePullPolicy: IfNotPresent
        name: web
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: iap-cert
spec:
  domains:
    - iap.wisv.ch
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: gce
    networking.gke.io/managed-certificates: iap-cert
spec:
  ingressClassName: "gce"
  defaultBackend:
    service:
      name: web-service
      port:
        number: 80
  rules:
  - host: iap.wisv.ch  # Replace with your desired domain
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: web-service
            port:
              number: 80
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-backendconfig
  namespace: default
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: iap
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: default
  annotations:
    cloud.google.com/backend-config: '{"default": "my-backendconfig"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    run: web
  type: NodePort
