apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: grafana
  namespace: default
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 3000
        requestPath: /api/health
    logConfig:
      enabled: true
  targetRef:
    group: ""
    kind: Service
    name: grafana
