apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: "7.0.x"
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    serviceAccount:
      create: true
      name: grafana
      annotations:
        iam.gke.io/gcp-service-account: grafana@wisvch.iam.gserviceaccount.com
    grafana.ini:
      instance_name: "W.I.S.V. Christiaan Huygens Metrics"
      security:
        disable_initial_admin_creation: false
        disable_gravatar: true
      analytics:
        reporting_enabled: false
      users:
        viewers_can_edit: true
      profile:
        enabled: false
      news:
        news_feed_enabled: false
      auth.jwt:
        # By default, auth.jwt is disabled.
        enabled: true
        # HTTP header to look into to get a JWT token.
        header_name: x-goog-iap-jwt-assertion
        # Specify a claim to use as a username to sign in.
        username_claim: sub
        # Specify a claim to use as an email to sign in.
        email_claim: email
        # auto-create users if they are not already matched
        auto_sign_up: true
        jwk_set_url: https://www.gstatic.com/iap/verify/public_key-jwk
        # Cache TTL for data loaded from http endpoint.
        cache_ttl: 60m
        # This can be seen as a required "subset" of a JWT Claims Set.
        expect_claims: '{"iss": "https://cloud.google.com/iap","aud": "/projects/966138216790/global/backendServices/7418003389199337678"}'
    persistence:
      enabled: true
      size: 1Gi
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: victoriametrics
            type: prometheus
            orgId: 1
            url: http://victoriametrics-victoria-metrics-single-server:8428
            access: proxy
            isDefault: true
            updateIntervalSeconds: 10
            editable: false
          - name: Google Cloud Monitoring
            type: stackdriver
            access: proxy
            jsonData:
              defaultProject: wisvch
              authenticationType: gce
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: true
            editable: false
            options:
              path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        victoriametrics:
          gnetId: 10229
          revision: 23
          datasource: victoriametrics
        kubernetes:
          gnetId: 14205
          revision: 1
          datasource: victoriametrics
        flux:
          url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/main/monitoring/configs/dashboards/cluster.json
        flux-control:
          url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/main/monitoring/configs/dashboards/control-plane.json
    ingress:
      enabled: false
