apiVersion: apps/v1
kind: Deployment
metadata:
  name: passes
  namespace: default
  labels:
    app: passes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passes
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: passes
    spec:
      volumes:
        - name: secret
          secret:
            secretName: passes-keys
            defaultMode: 420
      containers:
        - name: passes
          image: ghcr.io/wisvch/passes:20250526-9b69b1c # {"$imagepolicy": "flux-system:passes"}
          imagePullPolicy: IfNotPresent
          env:
            - name: APPLE_PASS_TYPE_IDENTIFIER
              valueFrom:
                secretKeyRef:
                  name: passes
                  key: applePassTypeIdentifier
            - name: APPLE_TEAM_IDENTIFIER
              valueFrom:
                secretKeyRef:
                  name: passes
                  key: appleTeamIdentifier
            - name: CERTIFICATE_PATH
              valueFrom:
                secretKeyRef:
                  name: passes
                  key: certificatePath
            - name: CERTIFICATE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: passes
                  key: certificatePassword
            - name: TEMPLATE_PATH
              value: "/usr/local/bin/Event.pass"
          volumeMounts:
            - mountPath: /keys
              name: secret
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources: # typical usage cpu: 0.00008, mem: 3.5MiB
            limits:
              cpu: 2m
              memory: 16Mi
