apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: passes
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./passes
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    replicaCount: 1
    tlsSecret: wisvch-tls
    serviceAccountSecretName: passes
    serviceAccountSecretKey: serviceAccount
    image:
      repository: ghcr.io/wisvch/passes
      tag: 20230929-ecb3267 # {"$imagepolicy": "flux-system:passes:tag"}
      volumes:
        - name: passes-keys
          secret:
            defaultMode: 420
            secretName: passes-keys