---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  namespace: default
  name: keycloak
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        requestPath: /health/live # TODO health endpoint?
    logConfig:
      enabled: true
  targetRef:
    group: ""
    kind: Service
    name: keycloak
