apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: keycloak
  namespace: flux-system
spec:
  image: quay.io/keycloak/keycloak
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: keycloak
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: keycloak
  filterTags:
    pattern: "^(?P<ts>.*)-[a-fA-F0-9]+"
    extract: "$ts"
  policy:
    semver:
      range: '>=21.0.0'
