apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: keycloak-disk
  labels:
    app: keycloak
spec:
  storageClassName: "standard-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
