apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik-operator
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik-operator
      version: "0.2.1"
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: authentik-operator
        namespace: flux-system
