kind: ProtectedApplication
apiVersion: gkebackup.gke.io/v1alpha2
metadata:
  name: listmonk
  namespace: default
  labels:
    app.kubernetes.io/name: listmonk
spec:
  resourceSelection:
    type: Selector
    selector:
      matchLabels:
        app.kubernetes.io/name: listmonk
