apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: listmonk
  namespace: flux-system
spec:
  image: listmonk/listmonk
  interval: 1h
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: listmonk
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: listmonk
  policy:
    semver:
      range: '>=2.5.0'
