apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: listmonk
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: ./listmonk
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    postgres:
      initTables: true
  valuesFrom:
    - kind: Secret
      name: postgres
      valuesKey: host
      targetPath: postgres.host
    - kind: Secret
      name: listmonk
      valuesKey: postgresUser
      targetPath: postgres.user
    - kind: Secret
      name: listmonk
      valuesKey: postgresPassword
      targetPath: postgres.password
    - kind: Secret
      name: listmonk
      valuesKey: adminUser
      targetPath: admin.username
    - kind: Secret
      name: listmonk
      valuesKey: adminPassword
      targetPath: admin.password