apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: listmonk
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: listmonk
      version: "0.1.x"
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: deliveryhero
        namespace: flux-system
  value:
    replicaCount: 1
    postgresql:
      enable: true
    database:
      init: true
  valuesFrom:
    - kind: Secret
      name: postgres
      valuesKey: host
      targetPath: database.host
    - kind: Secret
      name: listmonk
      valuesKey: postgresUser
      targetPath: database.username
    - kind: Secret
      name: listmonk
      valuesKey: postgresPassword
      targetPath: database.password