apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: listmonk
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: ./listmonk
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    image:
      repository: listmonk/listmonk
      tag: v3.0.0 # {"$imagepolicy": "flux-system:listmonk:tag"}
    domain: list.wisv.ch
  valuesFrom:
    - kind: Secret
      name: postgres
      valuesKey: host
      targetPath: postgres.host
    - kind: Secret
      name: postgres
      valuesKey: username
      targetPath: postgres.user
    - kind: Secret
      name: postgres
      valuesKey: password
      targetPath: postgres.password
    - kind: Secret
      name: listmonk
      valuesKey: adminUser
      targetPath: admin.username
    - kind: Secret
      name: listmonk
      valuesKey: adminPassword
      targetPath: admin.password
