apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: listmonk
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: adminer
      version: "0.1.x"
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: listmonk
        namespace: flux-system