apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: listmonk
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: ./listmonk
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    serviceAccountName: listmonk
    image:
      repository: listmonk/listmonk
      # tag: v5.0.1 # {"$imagepolicy": "flux-system:listmonk:tag"}
      tag: v5.0.0
    domain: list.wisv.ch
    postgres:
      host: 127.0.0.1
      port: 5432
      name: listmonk
      user: listmonk@wisvch.iam
      password: listmonk
      cloudSQL: true
      cloudSQLProxy:
        instanceConnectionName: wisvch:europe-west4:geurt
  valuesFrom:
    - kind: Secret
      name: listmonk
      valuesKey: adminUser
      targetPath: admin.username
    - kind: Secret
      name: listmonk
      valuesKey: adminPassword
      targetPath: admin.password
