apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: budibase
  namespace: budibase
spec:
  interval: 30m
  chart:
    spec:
      chart: budibase
      version: "2.5.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: budibase
        namespace: flux-system
  values:
    ingress:
      hosts:
      - host: budibase.wisv.ch
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-service
                port:
                  number: 10000
    
---

apiVersion: v1
kind: Namespace
metadata:
  name: budibase