apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/_clusters/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
