apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: requirements
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./requirements
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
