apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: chpay
  namespace: flux-system
spec:
  image: ghcr.io/wisvch/chpay
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: chpay
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: chpay
  filterTags:
    pattern: "^[0-9]{8}-(?P<run>[0-9]+)-[a-fA-F0-9]+$"
    extract: "$run"
  policy:
    numerical:
      order: asc
