apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: flitcie
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: ./flitcie
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    replicaCount: 0
    serviceAccountName: flitcie
    mysql:
      port: 3306
      cloudSQL: true
