apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flitcie
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: ./flitcie
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    process_on_start: true
    replicaCount: 1
