apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: authentik-ch
  namespace: flux-system
spec:
  image: ghcr.io/wisvch/authentik
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: authentik-ch
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: authentik-ch
  filterTags:
    pattern: "^(?P<ts>.*)-[a-fA-F0-9]+"
    extract: "$ts"
  policy:
    numerical:
      order: asc
