apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik-auth
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: "2023.4.x"
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    authentik:
      avatars: "none"
      postgresql:
        name: "authentik"
    image:
      repository: "ghcr.io/wisvch/authentik"
      tag: "1683387822-52c92b0" # {"$imagepolicy": "flux-system:authentik-ch:tag"}
    env:
      AUTHENTIK_BOOTSTRAP_TOKEN: AUTHENTIK_TEMP_AUTH_TOKEN
    ingress:
      enabled: true
      hosts:
        - host: login.wisv.ch
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - secretName: wisvch-tls
          hosts:
            - login.wisv.ch
    redis:
      enabled: true
      master:
        persistence:
          size: 2Gi
  valuesFrom:
    - kind: Secret
      name: postgres
      valuesKey: host
      targetPath: authentik.postgresql.host
    - kind: Secret
      name: postgres
      valuesKey: username
      targetPath: authentik.postgresql.user
    - kind: Secret
      name: postgres
      valuesKey: password
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik
      valuesKey: secret
      targetPath: authentik.secret_key
