apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: chipcie-nwerc-2023
  namespace: flux-system
spec:
  image: ghcr.io/wisvch/nwerc-2023
  interval: 15m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: chipcie-nwerc-2023
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: nwerc-2023
  filterTags:
    pattern: "^(?P<ts>.*)-[a-fA-F0-9]+"
    extract: "$ts"
  policy:
    numerical:
      order: asc
