apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chipcie-nwerc-2023
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./static-site
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    nameOverride: chipcie-nwerc-2023
    fullnameOverride: chipcie-nwerc-2023
    tlsSecret: chipcie-contests-tls
    domain: 2023.nwerc.eu
    replicaCount: 1
    containerPort: 8080
    service:
      type: ClusterIP
      port: 80
    image:
      repository: ghcr.io/wisvch/nwerc-2023
      tag: 20230303-b6cc089 # {"$imagepolicy": "flux-system:nwerc-2023:tag"}
      pullPolicy: IfNotPresent
      pullSecrets: {}
