apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nwerc-2023
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./static-site
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    nameOverride: nwerc-2023
    fullnameOverride: nwerc-2023
    domains:
    - 2023.nwerc.eu
    replicaCount: 1
    containerPort: 8080
    service:
      type: ClusterIP
      port: 80
    image:
      repository: ghcr.io/wisvch/nwerc-2023
      tag: 20231126-f56da4d # {"$imagepolicy": "flux-system:nwerc-2023:tag"}
      pullPolicy: IfNotPresent
      pullSecrets: {}
