apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hackdelft
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./hackdelft
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    defaultEdition: "2026"
    tlsSecret: hackdelft-tls
    domains:
      - hackdelft.nl
      - hackdelft.com
    editions:
      "2026":
        replicaCount: 1
        containerPort: 8080
        service:
          type: ClusterIP
          port: 80
        image:
          repository: ghcr.io/wisvch/hackdelft-2026
          tag: 20260220-e75e0b0 # {"$imagepolicy": "flux-system:hackdelft-2026:tag"}
          pullPolicy: IfNotPresent
          pullSecrets: {}
      "2024":
        replicaCount: 1
        containerPort: 8080
        service:
          type: ClusterIP
          port: 80
        image:
          repository: ghcr.io/wisvch/hackdelft-2024
          tag: 20240802-c64e948 # {"$imagepolicy": "flux-system:hackdelft-2024:tag"}
          pullPolicy: IfNotPresent
          pullSecrets: {}
      "2022":
        replicaCount: 1
        containerPort: 8080
        service:
          type: ClusterIP
          port: 80
        image:
          repository: ghcr.io/wisvch/hackdelft-2022
          tag: 20220502-6dd5cd2 # {"$imagepolicy": "flux-system:hackdelft-2022:tag"}
          pullPolicy: IfNotPresent
          pullSecrets: {}
      "2019":
        replicaCount: 1
        containerPort: 8080
        service:
          type: ClusterIP
          port: 80
        image:
          repository: ghcr.io/wisvch/hackdelft-2019
          tag: "61" # {"$imagepolicy": "flux-system:hackdelft-2019:tag"}
          pullPolicy: IfNotPresent
          pullSecrets: {}
      "2018":
        replicaCount: 1
        containerPort: 8080
        service:
          type: ClusterIP
          port: 80
        image:
          repository: ghcr.io/wisvch/hackdelft-2018
          tag: "75" # {"$imagepolicy": "flux-system:hackdelft-2018:tag"}
          pullPolicy: IfNotPresent
          pullSecrets: {}
      "2017":
        replicaCount: 1
        containerPort: 3000
        service:
          type: ClusterIP
          port: 80
        image:
          repository: ghcr.io/wisvch/hackdelft-2017
          tag: "41" # {"$imagepolicy": "flux-system:hackdelft-2017:tag"}
          pullPolicy: IfNotPresent
          pullSecrets: {}
