apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: match-rally-disk
  labels:
    app: match-rally
spec:
  storageClassName: "standard-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 555Gi
