apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: bt-website
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./static-site
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    fullnameOverride: bt-website
    domains:
      - businesstour.ch.tudelft.nl
      - businesstour.wisv.ch
    replicaCount: 1
    containerPort: 8080
    service:
      type: ClusterIP
      port: 80
    image:
      repository: ghcr.io/wisvch/btwebsite2024
      tag: 20240314-c94f43f # {"$imagepolicy": "flux-system:bt-website:tag"}
      pullPolicy: IfNotPresent
      pullSecrets: {}
