apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: "6.48.x"
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    grafana.ini:
      instance_name: "W.I.S.V. Christiaan Huygens Metrics"
      security:
        disable_initial_admin_creation: true
        disable_gravatar: true
      analytics:
        reporting_enabled: false
      users:
        viewers_can_edit: true
      auth:
        anonymous:
          enabled: true
          org_role: Admin
    persistence:
      enabled: true
      size: 1Gi
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: victoriametrics
            type: prometheus
            orgId: 1
            url: http://victoriametrics-victoria-metrics-single-server:8428
            access: proxy
            isDefault: true
            updateIntervalSeconds: 10
            editable: false
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: true
            editable: false
            options:
              path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        ingress:
          gnetId: 9614
          revision: 1
          datasource: victoriametrics
        victoriametrics:
          gnetId: 10229
          revision: 23
          datasource: victoriametrics
        kubernetes:
          gnetId: 14205
          revision: 1
          datasource: victoriametrics
        flux:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/monitoring-config/dashboards/cluster.json
    ingress:
      enabled: false
