apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoriametrics
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: victoria-metrics-single
      version: "0.8.x"
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
  values:
    server:
      retentionPeriod: "1w"
      persistentVolume:
        size: 4Gi
      statefulSet:
        enabled: false
      scrape:
        enabled: true
      ingress:
        enabled: false
