apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: areafiftylan
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./areafiftylan
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    replicaCount: 1
    tlsSecret: areafiftylan-tls
    domains:
      - dev.areafiftylan.nl
    image:
      repository: ghcr.io/areafiftylan/areafiftylan
      tag: 1670445502-619eac9 # {"$imagepolicy": "flux-system:areafiftylan:tag"}
