apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: areafiftylan
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./areafiftylan
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    replicaCount: 1
    tlsSecret: areafiftylan-tls
    domains:
      - dev.areafiftylan.nl
    image:
      repository: ghcr.io/areafiftylan/areafiftylan
      tag: 1675306733-619eac9 # {"$imagepolicy": "flux-system:areafiftylan:tag"}
    postgres:
      database: areafiftylan
  valuesFrom:
    - kind: Secret
      name: postgres
      valuesKey: host
      targetPath: postgres.host
    - kind: Secret
      name: postgres
      valuesKey: port
      targetPath: postgres.port
    - kind: Secret
      name: postgres
      valuesKey: username
      targetPath: postgres.username
    - kind: Secret
      name: postgres
      valuesKey: password
      targetPath: postgres.password
