apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transip-webhook
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: transip-webhook
      version: "0.1.x"
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: transip-webhook
        namespace: flux-system
  values:
    certManager:
      namespace: default
