apiVersion: apps/v1
kind: Deployment
metadata:
  name: annugame
  namespace: default
  labels:
    app: annugame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: annugame
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: annugame
      labels:
        app: annugame
    spec:
      containers:
        - name: annugame24
          image: ghcr.io/wisvch/annugame24:20250227-33041d7 # {"$imagepolicy": "flux-system:annugame"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 150Mi
        - name: annugame-leaderboard
          image: ghcr.io/wisvch/annugame-leaderboard:20250228-d00943b # {"$imagepolicy": "flux-system:annugame-leaderboard"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: backend
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/
              port: backend
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/
              port: backend
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 150Mi
          env:
            - name: "BASE"
              value: "/api"
            - name: "DB_BASE"
              value: "/db"
          volumeMounts:
            - mountPath: /db
              name: annugame-data
      volumes:
        - name: annugame-data
          persistentVolumeClaim:
            claimName: annugame-disk
