---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  namespace: default
  name: annugame
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 80
        requestPath: /
    logConfig:
      enabled: true
  targetRef:
    group: ""
    kind: Service
    name: annugame