apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: annugame-storage
  labels:
    app: annugame
spec:
  storageClassName: "standard-retain"
  volumeName: annugame-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
