apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: victoriametrics
  namespace: flux-system
spec:
  interval: 30m
  url: https://victoriametrics.github.io/helm-charts/
