apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: wisvch
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/WISVCH/charts.git
  ref:
    branch: main
