apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: wisvch
  namespace: flux-system
spec:
  interval: 15m
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/WISVCH/charts.git
