kind: ProtectedApplication
apiVersion: gkebackup.gke.io/v1alpha2
metadata:
  name: website
  namespace: default
spec:
  resourceSelection:
    type: Selector
    selector:
      matchLabels:
        app: website
