kind: ProtectedApplication
apiVersion: gkebackup.gke.io/v1alpha2
metadata:
  name: wiki
  namespace: default
  labels:
    app: wiki
spec:
  resourceSelection:
    type: Selector
    selector:
      matchLabels:
        app: wiki
