apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: default
  name: wiki-storage
  labels:
    app: wiki
spec:
  storageClassName: "standard-retain"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: wiki-storage
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/wisvch/zones/europe-west4-c/disks/wiki-storage
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: wiki-storage
  labels:
    app: wiki
spec:
  storageClassName: "standard-retain"
  volumeName: wiki-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
