apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wiki
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./wiki
      version: "0.2.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    replicaCount: 1
    domain: wiki.wisv.ch
    image:
      repository: ghcr.io/wisvch/wiki
      tag: 20230727-fe4b8cf # {"$imagepolicy": "flux-system:wiki:tag"}
  valuesFrom:
    - kind: Secret
      name: wiki
      valuesKey: iap_expected_audience
      targetPath: iap.expected_audience
---
apiVersion: v1
kind: Service
metadata:
  name: wiki
  namespace: default
  annotations:
    cloud.google.com/backend-config: '{"default": "ch-iap-backendconfig"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    run: wiki
  type: NodePort
