apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wiki
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./wiki
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    replicaCount: 1
    domain: wiki.wisv.ch
    image:
      repository: ghcr.io/wisvch/wiki
      tag: 20230812-e604e47 # {"$imagepolicy": "flux-system:wiki:tag"}
  valuesFrom:
    - kind: Secret
      name: wiki
      valuesKey: iap_expected_audience
      targetPath: iap.expected_audience
---
# https://cloud.google.com/kubernetes-engine/docs/how-to/configure-gateway-resources#configure_iap
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: wiki-backend-policy
  namespace: default
spec:
  default:
    iap:
      enabled: true
      oauth2ClientSecret:
        name: iap-secret
      clientID: 966138216790-us6sue108a879v3vk2om9inn3ftpobkg.apps.googleusercontent.com
  targetRef:
    group: ""
    kind: Service
    name: wiki
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: wiki-route
  namespace: default
spec:
  parentRefs:
  - kind: Gateway
    name: gateway
  hostnames:
  - wiki.wisv.ch
  rules:
  - backendRefs:
    - name: wiki
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wiki
  namespace: default
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    run: wiki
  type: ClusterIP
