apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect
  namespace: default
  labels:
    app: connect
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: connect
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: connect
    spec:
      serviceAccountName: connect
      containers:
        - name: connect
          env:
            - name: JAVA_OPTS
              value: -Xms400m -Xmx400m -XX:+ExitOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -Dspring.config.location=/connect/application.properties -Dspring.profiles.active=production
          image: ghcr.io/wisvch/connect:20231202-87a802f # {"$imagepolicy": "flux-system:connect"}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
          volumeMounts:
            - mountPath: /connect
              name: connect
              readOnly: true
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.0.0
          args:
            - "--structured-logs"
            - "--private-ip"
            - "--port=5432"
            - "-i" # Enables automatic authentication through the serviceaccount
            - "wisvch:europe-west4:geurt"
          securityContext:
            runAsNonRoot: true
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: connect
          secret:
            defaultMode: 420
            secretName: connect
