apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staticsites
  namespace: default
spec:
  secretName: staticsites-tls
  duration: 2160h
  renewBefore: 360h
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  usages:
    - server auth
    - client auth
  dnsNames:
    - "lustrum.ch"
    - "eerstejaarsweekend.nl"
  issuerRef:
    kind: Issuer
    name: transip
