apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wisvch
  namespace: default
spec:
  secretName: wisvch-tls
  duration: 2160h
  renewBefore: 360h
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  usages:
    - server auth
    - client auth
  dnsNames:
    - "wisv.ch"
    - "*.wisv.ch"
  issuerRef:
    kind: Issuer
    name: transip
