apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wiki2
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./wiki2
      version: "0.2.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    replicaCount: 1
    tlsSecret: wisvch-tls
    domain: wiki2.wisv.ch
    image:
      repository: ghcr.io/wisvch/wiki2
      tag: 20230604-cfdbc04 # {"$imagepolicy": "flux-system:wiki2:tag"}
---
apiVersion: v1
kind: Service
metadata:
  name: wiki2
  namespace: default
  annotations:
    cloud.google.com/backend-config: '{"default": "ch-iap-backendconfig"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    run: web
  type: NodePort
