apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mand
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./mand
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    replicaCount: 1
    image:
      repository: ghcr.io/wisvch/mand
      tag: 20240302-dec76bd # {"$imagepolicy": "flux-system:mand:tag"}
    auth:
      url: https://connect.ch.tudelft.nl
      clientId: mand
    postgres:
      name: mand
    mand:
      allowedGroup: staff
    domains:
      - wisv.ch
  valuesFrom:
    - kind: Secret
      name: postgres
      valuesKey: host
      targetPath: postgres.host
    - kind: Secret
      name: postgres
      valuesKey: port
      targetPath: postgres.port
    - kind: Secret
      name: mand
      valuesKey: pg-username
      targetPath: postgres.username
    - kind: Secret
      name: mand
      valuesKey: pg-password
      targetPath: postgres.password
    - kind: Secret
      name: mand
      valuesKey: clientSecret
      targetPath: auth.clientSecret
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  namespace: default
  name: mand
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        host: wisv.ch
        requestPath: /healthz
    logConfig:
      enabled: true
  targetRef:
    group: ""
    kind: Service
    name: mand-external
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  namespace: default
  name: mand-internal
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        host: wisv.ch
        requestPath: /healthz
    logConfig:
      enabled: true
  targetRef:
    group: ""
    kind: Service
    name: mand-internal
