apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: default
  labels:
    app: website
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: website
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: website
      labels:
        app: website
        access-dienst2: "true"
    spec:
      serviceAccountName: website
      initContainers:
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.13.0
          restartPolicy: Always
          args:
            - "--structured-logs"
            - "--private-ip"
            - "--port=3306"
            - "-i"
            - "wisvch:europe-west4:cees"
          securityContext:
            runAsNonRoot: true
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 20m
              memory: 100Mi
      containers:
        - name: website
          image: ghcr.io/wisvch/website:20260614-7ecf625 # {"$imagepolicy": "flux-system:website"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: backend-http
              containerPort: 80
              protocol: TCP
          env:
            - name: WORDPRESS_DB_HOST
              value: 127.0.0.1
            - name: WORDPRESS_DB_NAME
              value: website
            - name: WORDPRESS_DB_USER
              value: website # authentication via IAM
            - name: WORDPRESS_DB_PREFIX
              value: chtud59_
            - name: HTTP_HOST
              value: ch.tudelft.nl
            - name: VARNISH_SVC_SERVICE_HOST
              value: 127.0.0.1:8080
            - name: DIENST2_API_URL
              value: http://dienst2.default.svc.cluster.local./ldb/api/v3/
            - name: DIENST2_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: website
                  key: dienst2-api-token
            - name: W3CIE_THEME
              value: https://github.com/WISVCH/rechallenge/archive/master.zip
            - name: W3CIE_PLUGINS
              value: disable-comments,disable-search,post-types-order,daggerhart-openid-connect-generic,https://github.com/WISVCH/wisvch-wordpress-plugin/archive/master.zip,depublish-posts,redirection,ewww-image-optimizer,photo-gallery,https://github.com/WISVCH/zettle-stock/archive/master.zip,varnish-http-purge
            - name: APACHE_LOG_DIR
              value: /var/log/apache/
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: 50m
              memory: 500Mi
          securityContext:
            runAsNonRoot: false # FIXME: run as an unprivileged user
          startupProbe:
            httpGet:
              path: /wp-json/
              port: backend-http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /wp-json/
              port: backend-http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - mountPath: /var/www/html/wp-content
              name: website-storage
        - name: varnish
          image: varnish:6.0.18
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: VARNISH_HTTP_PORT
              value: "8080"
            - name: VARNISH_SIZE
              value: "128M"
          resources:
            limits:
              memory: 384Mi
            requests:
              cpu: 10m
              memory: 128Mi
          volumeMounts:
            - name: varnish-config
              mountPath: /etc/varnish/
            - name: varnish-storage
              mountPath: /var/lib/varnish
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: website-storage
          persistentVolumeClaim:
            claimName: website-storage
        - name: varnish-config
          configMap:
            name: varnish-vcl
            items:
              - key: default.vcl
                path: default.vcl
        - name: varnish-storage
          emptyDir: {}
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  namespace: default
  name: website
spec:
  default:
    checkIntervalSec: 60
    timeoutSec: 30
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        requestPath: /healthcheck
    logConfig:
      enabled: true
  targetRef:
    group: ""
    kind: Service
    name: website
