apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: website
  namespace: default
  labels:
    app: website
spec:
  parentRefs:
  - kind: Gateway
    namespace: gateway-infra
    name: gateway
  hostnames:
  - ch.tudelft.nl
  - www.ch.tudelft.nl
  rules:
  - backendRefs:
    - name: varnish-svc
      port: 80
  - matches:
    - path:
        value: "/choice2"
    backendRefs:
    - name: choice-internal
      port: 80
  - matches:
    - path:
        value: "/events"
    backendRefs:
    - name: events
      port: 80
  - matches:
    - path:
        value: "/choice2/api"
    backendRefs:
    - name: choice-external
      port: 80
  - matches:
    - path:
        value: "/wiki"
    backendRefs:
    - name: wiki
      port: 80
