apiVersion: v1
kind: PersistentVolume
metadata:
  name: website-storage
spec:
  storageClassName: "standard-retain"
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: website-storage
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/wisvch/zones/europe-west4-c/disks/website-storage
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: website-storage
spec:
  storageClassName: "standard-retain"
  volumeName: website-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
