apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: website-varnish
  namespace: default
spec:
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 30s
  selector:
    matchLabels:
      app: website
