apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
data:
  config.js: |
    module.exports = {
      platform: 'github',
      autodiscover: false,
      repositories: ['WISVCH/chpay', 'WISVCH/keycloak-build', 'WISVCH/website', 'WISVCH/wiki', 'WISVCH/mand', 'WISVCH/narrowcast-content'],
      onboarding: true,
      onboardingConfig: {
        $schema: 'https://docs.renovatebot.com/renovate-schema.json',
        extends: [
          'config:recommended',
          ':automergeStableNonMajor',
          ':configMigration',
          ':rebaseStalePrs',
        ],
      },
      requireConfig: 'required',
      platformCommit: 'enabled',
    };
