apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
data:
  config.js: |
    module.exports = {
      platform: 'github',
      autodiscover: true,
      onboarding: true,
      onboardingConfig: {
        $schema: 'https://docs.renovatebot.com/renovate-schema.json',
        extends: ['github>WISVCH/renovate-config'],
      },
      requireConfig: 'required',
      platformCommit: 'enabled',
    };
