apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-retain
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
parameters:
  type: pd-balanced
allowVolumeExpansion: true
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
