apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: choice
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./choice
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    replicaCount: 1
    tlsSecret: wisvch-tls
    domain: choice.wisv.ch
    image:
      repository: ghcr.io/wisvch/choice
      tag: 20230502-74bf65e # {"$imagepolicy": "flux-system:choice:tag"}    
    oauth:
      issuer: https://connect.ch.tudelft.nl
      client:
        url: https://choice.wisv.ch
      scope: openid, profile, email, auth
      groups:
        admin: beheer,bestuur,vc,epa
    postgres:
      database: choice
    hibernate:
      generateDdl: true
      hb2mddl:
        auto: validate
    flyway:
      enable: false
  valuesFrom:
    - kind: Secret
      name: postgres-new
      valuesKey: host
      targetPath: postgres.host
    - kind: Secret
      name: postgres-new
      valuesKey: port
      targetPath: postgres.port
    - kind: Secret
      name: postgres-new
      valuesKey: username
      targetPath: postgres.username
    - kind: Secret
      name: postgres-new
      valuesKey: password
      targetPath: postgres.password
    - kind: Secret
      name: choice
      valuesKey: connect-client-secret
      targetPath: oauth.client.secret
