apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish-proxy
  namespace: default
  labels:
    app: varnish-proxy
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: varnish-proxy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: varnish-proxy
      labels:
        app: varnish-proxy
    spec:
      containers:
        - name: varnish
          image: million12/varnish 
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: VCL_CONFIG
              value: /etc/varnish/default.vcl
          volumeMounts:
            - name: varnish-config
              mountPath: /etc/varnish/
      volumes:
        - name: varnish-config
          configMap:
            name: varnish-vcl
            items:
              - key: default.vcl
                path: default.vcl