apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: github-webhook-receiver
  namespace: flux-system
spec:
  parentRefs:
  - kind: Gateway
    namespace: gateway-infra
    name: gateway
  hostnames:
    - flux.wisv.ch
  rules:
  - matches:
    backendRefs:
    - name: webhook-receiver
      port: 80