apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: github-webhook-receiver
  namespace: flux-system
spec:
  rules:
    - host: flux.wisv.ch
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: webhook-receiver
                port:
                  number: 80
  tls:
    - hosts:
        - flux.wisv.ch
      secretName: wisvch-tls
