apiVersion: v1
kind: Secret
metadata:
  name: authentik
  namespace: default
data:
  secret: ENC[AES256_GCM,data:6Wswtn+xxWJWxKGZMCvUwHnuCZT9HC+sRmcqa9EVpatcZCbaL0EFdj0EhBSup2Ruk3YNqGGx+vHBNGc6HG5Jus6oocKjrBv4UJv2T2P5MDebn96k+T0QnZGgTEAKCt9LTrKWo8Hw5CsQZLko2lmayWXBqOS+k2sxU6WwmagMNs4E+XcSNnm2K5mvTpSwu4DKbYw2rYvW2Bk30AExpkDhDOTK+UQeH+9oMRESUw==,iv:sTl7HR+h88lyvqK55JFpfxIcr0F+hO0cBN4P/EqfzAc=,tag:lF4dI9GIhmNicG0cKifI7g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ug2fepnvaqsfpn7t5gjjh2l0j8074jwh9h50pnjcjxn08v8pp3xq7ymxn2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQVNSblJkdTRWendLc1pC
        NlFQSzlZWlhYYVFKU1B4TzdtRnJmUE4xOENNCnYvQnl3UmRiMW5rWXo3U3UvelA4
        eFpEaFU4aFk4OU9kdXFEb3owY1VtWjAKLS0tIGxvRGZnSU9wOEJ3NWtaN2JKSFY1
        RU5IYUVxdGtyNjV1c0lEOHViZ3dQeXcKpNDZWgwedzntZAOAC4Dt2HP50+YToETR
        f07HyTt/LgP4fTMEWqPMIL3DJhyBVpX7vO4rePzTJaa9A6ECIvd4Fw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2022-12-19T23:38:43Z"
  mac: ENC[AES256_GCM,data:ElIznV750VbHBSLviFKYHds/uA4SzrD+6/HyB8F0gC4Asi4rcPTFlbnzKA0PzXKPDDC2dqIkO+AHXoKIdLzQUvAFnusO4gDIPstY6N1AH92qNpaXy3Dsp3YEP7Z4SgcV/P03foehrGz6eE+VkkUCplar8HyHBri0HrD+UN2kS5I=,iv:0e9oVL928ubwzi/Gli8DPbaRBHHU+o1+UZO2Bg0Bq8E=,tag:Lbjs5kZTBlPXUl6QV64wZA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
