apiVersion: v1
kind: Secret
metadata:
    name: choice
    namespace: default
stringData:
    pg-username: ENC[AES256_GCM,data:kek50ZC3,iv:r7VPWD9z+67UjjBG6gRo6ZjChV9A7pwpNDG70xIQEDE=,tag:XzVmmYz5/YE3nJXOiJH7IQ==,type:str]
    pg-password: ENC[AES256_GCM,data:bjo/j3zJmnQ+6jWf80hd/yfD97o=,iv:rq8ky09ZmtfYnGrKaD4ceZZUqcrng98wAilNiToGZHQ=,tag:R5Dz+MQleumCqrwfmv9YTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ug2fepnvaqsfpn7t5gjjh2l0j8074jwh9h50pnjcjxn08v8pp3xq7ymxn2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNXlzNXRzNDlTaVhxdGwy
            R2Y2Sk9pNlZaMm9xU2lSN0ROd1B4YUdZUG13ClBQcndydmEvcUs4RWhKRG9zVkw4
            aG9zaTdTK1BKeitDd2d6VkVoUHBEOHcKLS0tIGIvQWQ3L3hYMHU4UCtBZzZEMUV5
            bVVNRlN4SmNUVXFZeUcvdE9VanpkS2sKLivuSKpur34AeKgBjzdaOEtdcoqEzejw
            TYjH66Txmid4/HUKW1BQf3Dh+ZpUtFthK/jXNakXZJiWzdh7P1usBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-27T20:50:14Z"
    mac: ENC[AES256_GCM,data:aidKoc7TKMtKTJSuOQ9vzPxHuu4Hl/+fBGoxmHNwiKoefjvEzipksmw1Iu2qDE5/4SrA74cVtL9iJZzTeBkE38dqaxihdj4bdx4DNeyznmp7lj0MQBHPXw6/MwNF+DMKyRtP8vT/s1Vj+m929wLPSJpTwiu7GD1XSeZjYgZddm4=,iv:qxmyqeJjpge1ze0XkFnAj6mJm3JhfhU7Rf70siP35/o=,tag:mdkNpF67Pu2JqZBWVODniQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
