apiVersion: v1
kind: Secret
metadata:
    name: chpay
    namespace: default
stringData:
    mollie-key: ENC[AES256_GCM,data:HDpAq2EOyPcXtuo7s0hFRgQ4KIrsHqj5BR3aS36/EgTtAzY=,iv:sPVTmeT40czzcpTGDuoI+C2HAcCqeiqfAAjJVEvh+ws=,tag:4EZifSXOJclqPlWcgnAKDQ==,type:str]
    login-client-id: ENC[AES256_GCM,data:cJGI6jDhFtTANEv+hMh2RzxUug==,iv:pY6NnaE60SghEBVM1hOkUuEdMSozk/Xqsy0RlWy+76w=,tag:FHF5k/6t+3B3JMSGbb6IPw==,type:str]
    login-client-secret: ENC[AES256_GCM,data:sneL+roB+ZxvNvuKsdy20Gwx/HTyps6vP5UdarPGaLo=,iv:SjwsF7l+ilGrBxqE8IM3JvDg5ekv+uXGpDXOg3lu7tw=,tag:9IX1G0eMizs3390Bknx2bQ==,type:str]
    events-api-key: ENC[AES256_GCM,data:l2ttp+h7fb0WHdNxDEh2dSbofMstQh90AH3LqDCbBhjMBdFpsw6JQhGrzYyzCNSXjKk=,iv:EEt8a/xEHDHAjnftXiR/czSMUHdmxkB5m9FRV/YzqzU=,tag:t6O3NL774SXEl2Lo1ksCsw==,type:str]
    database-username: ENC[AES256_GCM,data:QUiadjQ=,iv:rQHbvgG61TJjvaGVldXT8jBvtTcqR5jro8ZqhmBjKRs=,tag:uvcxHfIaQ6/5qLx95vDVeA==,type:str]
    database-password: ENC[AES256_GCM,data:dO34yxnYZ3f9kT2TG2u9/Q1GDSEsuTGX3LgjSqLt47Ga0Ms4uZalv9+PyMUrAPYvOWI4PRTpwJ/x0gtQGXl+,iv:k6EK1qVQ/rsiOdnXWMijnwGKbkoUofxkrvrtAoFDqBE=,tag:kBOEcFemPpwoxuW67pFN8g==,type:str]
sops:
    age:
        - recipient: age1ug2fepnvaqsfpn7t5gjjh2l0j8074jwh9h50pnjcjxn08v8pp3xq7ymxn2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVGRXQzRpQlJVVVZ5dHps
            RU9pSjNSN3JsVHpURFBXYWx2NThwam9EU3lnClBqZ1I5WWd0aDFHMnZvT1g3OEJJ
            WmM2R252ZjM2OC94TUk4Rkd4bkFzQkkKLS0tIFNnTG1MeHBtSGZnV25qSjltKzB2
            YlpyWThJVCtUUVRNMVA3cDc5UW1qUlEKZ3skE+KpAmwpWJNn/ROxX8e5DGvdB/Iq
            kqABGrONZ16V2Us22PK574tVzGtUjJhMqHvb4ruK40NTjWHznEnRQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T20:27:12Z"
    mac: ENC[AES256_GCM,data:GWmzfz7FymkQPybAtAa2ykK0L5OsNXK31mB5JvWTCpu338ZpdrgV8snHjfEZFuQhZ/VsG6D+juWDC3fTnoiMFv/emATxq5dIgwLnDVWE38NDs4MKPqbmmSTqDwSu8bU9LiJ7X1qnKUsocfpY76VK7HOHM3ERHeLcRzx7j6t36HY=,iv:/HVk5KVqJO5OV1YEamoAcjN/24fIBjlbl3nSfL/5ZYA=,tag:HD3XWbn0k4FijuW3Ne3YhA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
