apiVersion: v1
kind: Secret
metadata:
    name: chpay
    namespace: default
stringData:
    mollie-key: ENC[AES256_GCM,data:2uxsp8taA9TVJyermcFxLT7uEI1c/vBsLGC9XGGlPnWGESE=,iv:a5JNDRzY633h/OiiNWn3+J2qhkr9kUlwvAV9Mh55GY8=,tag:eiR9KeWpnhmVU+uhXGoggw==,type:str]
    login-client-id: ENC[AES256_GCM,data:JycYz0RmikBDRld/U3glsygvsQ==,iv:WTdAKMOgJyledrF2mBmmb8tw03uxwNDe5FrvjNLXklI=,tag:Fei/W+C0ZvD3XpP+PoQq5Q==,type:str]
    login-client-secret: ENC[AES256_GCM,data:R7BUOf6e4YCvtppNu0WAOduF3Mg7nE9/cXbffLIxaCA=,iv:A+Yq1odkMSbrthDJBSIYvUoF62Ijvyg2/FieCfZE8/M=,tag:Pgg0PdqdZuPTucpFXZfi9A==,type:str]
    events-api-key: ENC[AES256_GCM,data:PHv6,iv:I9I0hZS09JPSllL0VqS8vcp3XMgcxJRa/+Mn6/4mI0M=,tag:Fzzdf7TO02UBrkhP/fnhGw==,type:str]
    database-username: ENC[AES256_GCM,data:mMTIvQg=,iv:GmKB6cqdjUHfi+QJvT40jZv4IhBnL3QOqM1B5VbuBTk=,tag:nGhpmcTG5oSaKCZBcFh/fg==,type:str]
    database-password: ENC[AES256_GCM,data:cE+LAxF/0586h8OzSXzIgWIHVAHJUe/ypX63INvDXrzbtqwRwPXqHx1BsxfwNiy2hkYm2aAgeXDrDdbkOQfL,iv:ozUNecrRpUzE/aqKCcYD5APiB5NCHNFiKtGtG19eUrA=,tag:4pw86X9oF/aT8EFp0t3FUA==,type:str]
sops:
    age:
        - recipient: age1ug2fepnvaqsfpn7t5gjjh2l0j8074jwh9h50pnjcjxn08v8pp3xq7ymxn2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBODVlQkxSZVNyZ203eDhM
            cFNXdEljYXR1VlRuY0xTYVpEY2cyOEIzQ0IwCklEeDJ4b1FUWDdpOEEzN24xa3NC
            MThvMW5KRThpejNqbldad2dVSE5ENE0KLS0tIHFlalE3alpuQkx1NjFWUE1Kc2Rx
            RklLVTNrVGNvYy9wYkJ1TWZSWk5Sd3cKU2PgfDbk5z5IXjSuQPNNEqqhKYeQDzUj
            jIT8cqFxy9QmOjVzwcqYeFCAhDcXyzQcrFdQUd8z6hSdwMUA6YJfpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-01T08:24:19Z"
    mac: ENC[AES256_GCM,data:NxoiAgWi9106TKkCC2MSBGN11QcD9b5MlO2YqZkgflUdaVH2KoDx5HMiGA0lbqSnE/+AOBCk02zHPHzaSXIWXeSTNmO4XjsCKdw5kV/GqJu4CJI25MzNkE3DcRln+y1uPDhalWqBQRKjyDasmD34MfUDmSznq+6K8+90Z4vUDBg=,iv:6E4mNfeMEkRmX6fkXPminqa0eg5und7UrxQmidycAic=,tag:85dn9+qNvvVcB4trnub7Tg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
