apiVersion: v1
kind: Secret
metadata:
    name: chpay
    namespace: default
stringData:
    mollie-key: ENC[AES256_GCM,data:HDpAq2EOyPcXtuo7s0hFRgQ4KIrsHqj5BR3aS36/EgTtAzY=,iv:sPVTmeT40czzcpTGDuoI+C2HAcCqeiqfAAjJVEvh+ws=,tag:4EZifSXOJclqPlWcgnAKDQ==,type:str]
    login-client-id: ENC[AES256_GCM,data:cJGI6jDhFtTANEv+hMh2RzxUug==,iv:pY6NnaE60SghEBVM1hOkUuEdMSozk/Xqsy0RlWy+76w=,tag:FHF5k/6t+3B3JMSGbb6IPw==,type:str]
    login-client-secret: ENC[AES256_GCM,data:sneL+roB+ZxvNvuKsdy20Gwx/HTyps6vP5UdarPGaLo=,iv:SjwsF7l+ilGrBxqE8IM3JvDg5ekv+uXGpDXOg3lu7tw=,tag:9IX1G0eMizs3390Bknx2bQ==,type:str]
    database-username: ENC[AES256_GCM,data:QUiadjQ=,iv:rQHbvgG61TJjvaGVldXT8jBvtTcqR5jro8ZqhmBjKRs=,tag:uvcxHfIaQ6/5qLx95vDVeA==,type:str]
    database-password: ENC[AES256_GCM,data:hzLFxFg=,iv:lt44/nCGOpFzpb8iguCKO39OK6hnFLkCCX5IPRdgfBQ=,tag:klPDPr2OFjsaPyglU8orKg==,type:str]
sops:
    age:
        - recipient: age1ug2fepnvaqsfpn7t5gjjh2l0j8074jwh9h50pnjcjxn08v8pp3xq7ymxn2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVGRXQzRpQlJVVVZ5dHps
            RU9pSjNSN3JsVHpURFBXYWx2NThwam9EU3lnClBqZ1I5WWd0aDFHMnZvT1g3OEJJ
            WmM2R252ZjM2OC94TUk4Rkd4bkFzQkkKLS0tIFNnTG1MeHBtSGZnV25qSjltKzB2
            YlpyWThJVCtUUVRNMVA3cDc5UW1qUlEKZ3skE+KpAmwpWJNn/ROxX8e5DGvdB/Iq
            kqABGrONZ16V2Us22PK574tVzGtUjJhMqHvb4ruK40NTjWHznEnRQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T15:40:04Z"
    mac: ENC[AES256_GCM,data:Tr7mVg1/IvyBJSwC7kjWpuhhuOJ6fjCVdFnGMEjAH/H8P9Jp+1H7uNEMJ+ganyHUx20EFanp8L6LaYdDKwxD+/zwba0zG6fPFLEzVWKnsnvG6rFNMOBNszxwrlSk66sbYm6qKZhWKRWRHiqJotcAr/BksSleUEYaeVCNEiOWhGc=,iv:cKF4c2uTO7mhb9kvw/fDmMz8TTpLm7hbEgthZ+JzPoQ=,tag:vfXGJudbLoky0TdlvPybjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
