apiVersion: v1
kind: Secret
metadata:
    name: connect-proxy
    namespace: default
stringData:
    client-id: ENC[AES256_GCM,data:dD+zoLl7ae9HYNfFBL9BejCGCb34lZrtR9oYPXW++hYRxzn7,iv:tmKBLqR+J/q3JLHaX540ElQZOLSo0eg2+4HgRjOYYps=,tag:bR9RPqitjA79ugg1UJhPvg==,type:str]
    client-secret: ENC[AES256_GCM,data:7w+rETdcwGctoy+qetvKBk2FcnUuIHqlSjUPBZkr7iYTE3T7wt+DXiW4v/XvoRCy5Q3o4X7a5k0jo5mgl7GJvCF/8w98lql2HCHN1rvmgnMhG5MOhG4=,iv:EMAqWVZyaRVgv9/r+T1mbtZCTYMmQcq+I69Xvkp2/rc=,tag:hPupCNT3KbYyBavfruAiXA==,type:str]
    client-cookie: ENC[AES256_GCM,data:73c7qFtIgVjVtEemCy8IKXQ+2jtIX2/qjknSd1eRQ76yMDCEUCU3aDuC3Wc=,iv:0Tc0ZM5ZDIyq616ombbew/b0IqahSJ0WWF5rNhqx4OQ=,tag:UZ8kfjXmBA0avzskNLa/KA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ug2fepnvaqsfpn7t5gjjh2l0j8074jwh9h50pnjcjxn08v8pp3xq7ymxn2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bDU0UE1FdFJjQ1ZxdzdB
            bS9EYlpuRFoxTUI1bG1ObXdIRVJBNXptNzJZCjNzMWRNcWxSWVcvZzcvbXBzOEg1
            WEZJdUZPT2lLRkthdEpFdGp5c1NEUkUKLS0tIFF1dGZyUFNSSmJIVEkrVDd6cnZy
            NENwUUpsRisrYlI0ejc3RVN5T2pld2MK84d66upCgu2y66xwnvw2FfXKMv5BwC+z
            NXRTh1aGHIkJt1vdCOxm5/ze5UwnJPsMTTSUxwDGXcQduWxtL9rRlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-03T15:28:39Z"
    mac: ENC[AES256_GCM,data:26xjEkUMgnZ/PE69NVzJypW2a/ehKLgS2fLeVY63hiewsSZbx7c+8If2DoSz0ZQSEId+wOSvXfid9PSOiAemoHQ6NZqy+y1f/kphK31nPZFGtI4yOSIDMRJPsc8hPD4Cy6AQ9ffu5LT2fywTeHR6jcH7dK/46bd7++VF3fJGWM8=,iv:7BlI/rUJpbFASyKPwGKvnx4opeMGpASJMpYj9hPr2lU=,tag:qOKG1bqEaccRVQSAbQ3flg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
