apiVersion: v1
kind: Secret
metadata:
    name: dienst2
    namespace: default
stringData:
    secret_key: ENC[AES256_GCM,data:xWy0/uBmQ7CeQtDLTwZk9AGfxDdSJphdqBqstNaHstebJjaUCSDC0Td9BMzAME+uSTc=,iv:UdoF+5FJY1QsBoNmP+3+lcox3G31Swb0MnGUMCw5RGI=,tag:QW3bq5uH2JSM1r03FeqxvA==,type:str]
    iap_expected_audience: ENC[AES256_GCM,data:kAa+729yUAnl6gawXaPWiFmnYxrNrv8acaUxbBpREV0OuQeGzyY7fqCkpn5u9KUoSleqSetQCHkon5ulYMYYD/g=,iv:ZorEevcCWniVgFb9AzjOSkYtoXEM6M1bkFmbg2rVWmg=,tag:2riVoqZSScA0zR6+qWswsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ug2fepnvaqsfpn7t5gjjh2l0j8074jwh9h50pnjcjxn08v8pp3xq7ymxn2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Q2t1TG5wWlFTQnV3Q0VZ
            NGp0MSt4Tk93RXl4VjliRUhJcjhkQUlDaGdrCnZzQWE5V3F3SjNTQzRmZnJub2My
            dXJvN25HZ2U5S25LRlU4TytrNXRuK0EKLS0tIHVnQURhK1AySEYwOTc1eEhFVWpD
            cjFlTFhaT1c3TnRKSlVxektCbGsrTHcKKWMFJlYuVxg9gIXOIqi+BC7AgR3kiRqW
            wN7WGTPDbaG+OSLt4nG4BWS0misR/hGocMm61JZvurdATHDHhGbYVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-03T14:46:47Z"
    mac: ENC[AES256_GCM,data:uOym6GtdaeKMBdqSztgbxmOHD3m+qvaSBFiKja3GZE85Qkq43gMyNuGrF/qIC0DIRpvhjn/lMZiyS8zqm+zbQMRfqYr2mowVdsZcmHcFCge7BDBljZLkVyX5RzRhYRaBpiLFdCipaiFx/zHPm+tmL4Nthc+zi+924PHQezRGBeM=,iv:pW3ahnCV+viG1ldOwaXUedeJEu3/gq9A3K8FAWRky3k=,tag:gbe9ahgci04mRlU6JLkNHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
