apiVersion: v1
kind: Secret
metadata:
    name: dienst2
    namespace: default
stringData:
    secret_key: ENC[AES256_GCM,data:GpUPlc36RUmRimsDPE989XuE1QGL0gLuGxoKKOk1Q5uGtmnvIsxC6C7xv1IcrHyb4PU=,iv:97C4YISZPgHUEAt0vAacFd8mcElutBecEfexc2sYvA0=,tag:hyqBzA6ay5UfEoH4gkdx6w==,type:str]
    iap_expected_audience: ENC[AES256_GCM,data:9TLnhej6bHxcpk2gIJdyP2c6wc8q6fgzJjRT09s+KWhY5Hk+3CpQ5k+jZaenT79dzWAz9wK53OGQ7Ljlpdw7fAc=,iv:sdI9k0u9fTWVzwoj3h6xO//JosKd6i/ao+JP7spzuVs=,tag:KI+X8MCeEa2CqZwJKhlh4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ug2fepnvaqsfpn7t5gjjh2l0j8074jwh9h50pnjcjxn08v8pp3xq7ymxn2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZU0ZZSGJoU2wxR0dlTmNM
            RmdrdjZUQitvQmRqcFBrUmZMaUV5cS9YMDNVCkRUcjJCZERMYjZOdmhpSjVQR1dC
            RWpqRGFRM21PR3A4Z1RudmN1c3pIaWcKLS0tIGQwMVU2YzlTMytTbXhKd2oyb05z
            MjloTmZEYnNqanJOOHIycFY0YS9sUVEKyJ2QhQO5Fec+uV1+A54b0zaDRKs8zvpx
            Nyr0ypa++JrLjpmQvyx9zuYF8t8ze5n8/ZV0a2g9TbwSFZBwjQreeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-09T10:00:41Z"
    mac: ENC[AES256_GCM,data:157k+iExL82BaqJ1t5rOG+XvL1OggTwbPv8Zwj9POvedHuVvpn+YOxryI7mcqRZEqHb3eC/uuesaRu6ZHA+h2OFC+Mn3ia0uqKCZJltzPkonrSqOIBTD0rHhA0IuKUkIe4eQDXLYp5KUG6xp3ZgZPT6wXCrtq2roOGOMsDUpsG8=,iv:cOvAA9CoNN8GCh8L7DHGQFDNYiB18XxQ6hW4A4P9CZE=,tag:YzMzB91JjNemVGeWRvktJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
