apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: default
data:
    address: ENC[AES256_GCM,data:qhzhgcRU1u8HvZEDFkzxiBtI06B5DF2IlT83iNuq0ST3TYW9i8O6+NCnTRUnLC9k6KxejYuGbh9P/y/azC/rvoPieHJ5IgmkP/lnPt7wfDKQI4UJItot5cubWQYrmWWCEB8ecDJ2SZqME6fMUzBE1k3FAkifWW4rAkPY0SjXqjk3UhE/lDQ4s5h3R9v3TBYiYCgUtYEZFXF+Yk1KQTCUGrGIXDU=,iv:YREArEhptdMDuqgeqGJ2gy1MN6EqQBJpGEPZfQqRkvc=,tag:DN6RzFbDOzioaK74A51PMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ug2fepnvaqsfpn7t5gjjh2l0j8074jwh9h50pnjcjxn08v8pp3xq7ymxn2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeklNVVZyM2xoand2V2tY
            ZVY2T3E4MzFmNDJxRzV0Y2VmTkRuTm15WGlVCmtRMXl2ekt0ai9FUUNhaG92VDd6
            RVpIY1JOZmNsWHNtSE1ZaWcrYkttbUEKLS0tIEU3eWY4a2huaXVERjA3TGQ4VnRN
            RnJtZUFXYXRXZURadkxBbUFKcjR1TWsKo98W7PoBudA2s8Y8wU3yEacGvMyqb+Fp
            nX3tIW/J1izvFjH3Mxs9p3+MFYBHF9f7GtONLqzYhq4DQcT0cVCw2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-19T17:24:38Z"
    mac: ENC[AES256_GCM,data:ZUZKPlM+UkrSM8QiqegijVno/kYNHurxQLzp3z+lJW4c3vD5YkMM1AQxed/uFj82a6Ve6rsDL+21D8XzNwf3PCuNw/CJFdCn2iERmzfTNpjj7FQ4Ac4mDIyljhya7b7/WpIxxBeEPKjALAfpFPa0hKlKE/z99gI/arDfFg2I3rA=,iv:rUGOCQ+VRK4fonCW9CtmhivaZs2tujvSpHcLXz5CUys=,tag:z1d50yrEiYlVCkt5dOWNGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
