apiVersion: v1
kind: Secret
metadata:
    name: feedback
    namespace: default
stringData:
    recaptcha-site: ENC[AES256_GCM,data:cA+WEBRv8kcrmzdMcK7LsF6TX50hx8fdVv+W6RXcZeh3O8CiZQH6WA==,iv:FdBGm1SewZsLZ0jB/wTuhMLljSQM8pnE/FvJhuN4uas=,tag:ef0fZkBjDL62x+bhabLkHw==,type:str]
    recaptcha-secret: ENC[AES256_GCM,data:wTaWg5q9qPKl5YQJfe/hOBRqc3oESgza96nNaY35HMC3SCslHkDBZw==,iv:qPlNUs/bSH7mSr94IA029dFQP4rdWnPo8RKJzRFUmiI=,tag:OcUJT1H0QwZco2hzLPxT5w==,type:str]
    connect-secret: ENC[AES256_GCM,data:MjetQ19mzK7oGeDPVgAqnDRAo/rMi9WdskSTiSHBwSP66ZTN6+EKZ6EtgRPhFtGwraQ3furS4OlbDioGGUzdHW3s+KyT7ea8TD7jrBCmTdrWfV3M3T4=,iv:qcz1wlyHJNDmh8/T69ZXZBnilLVwxzwUGKIlGIIsgIs=,tag:egHcMR+LnP7XHbnW2Zy+Cg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ug2fepnvaqsfpn7t5gjjh2l0j8074jwh9h50pnjcjxn08v8pp3xq7ymxn2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkd1lFOUN6aWV0NmtiTExq
            U1ZGd0RiUkx3cXlCeG11VjBvRWZyZzNTTGdJCmd5UHQvWklmQmlZby93cERPSnQy
            QXlRUWpyZmw4M3dtY1RjY094S2VOT0kKLS0tIDA2NDdGUWgyU2dhQkJURXBERExX
            dzFJYUZhM0dwNkltVDhNL0N5RHMweTgKgB1sUod8FtaZnY2PIaYON7f/oP/NMbrQ
            hZOJpkmxJ/+fwoq+l0JRd8NVqrNGpK4w/T4tfdhsqyLMTSGKCzZjCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-23T15:49:38Z"
    mac: ENC[AES256_GCM,data:1VRnlRfZ4Vq1XuKTndvvqxtZqtMCDHRFDXdK0TND5sMGUP6Kb+gVGjWX6PXOPJaqey7hfw5hfmaLnDjiWXm5m2S5tMKVsvK/B0+lwpCvB//pi6pP1wXaUv1SBmS5o4rlDUt8elffonbzHYNN+Y8KOfYss8vwmBcc6Ha8xXjDK5k=,iv:V+E4+EVmGS0PBYff/uh3K3KUGKvb3QQ9/ugGjsvoomo=,tag:tX0hyPrbYfmlLoiRF2sV8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
