apiVersion: v1
kind: Secret
metadata:
    name: iap
    namespace: default
stringData:
    clientId: ENC[AES256_GCM,data:ftcLXm4XLTSAewzl2Qn6YqzTUERuyvbNHzRwGMKBTcowqDLR2/k/hh5bK7QwI1C5WoC8VY+iSus4vFIexBqKsxZNJjqEm79D,iv:1q4ajDX7BUsxpiUURJEBIw79RTaaX5ROD90RKHTIaNI=,tag:qncoGEvGHQBgApeY71ALqw==,type:str]
    clientSecret: ENC[AES256_GCM,data:y1loxFq4WZRC7JN2SotRfhuu5p6zeQBnW2syCM7ozeJ7J1U=,iv:7tT6IUC33VE0wjFKgzT9iwveRdHBbhNJFfBRHoQI4Ds=,tag:Bcw+EjWFRucNwhxiLZ2wvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ug2fepnvaqsfpn7t5gjjh2l0j8074jwh9h50pnjcjxn08v8pp3xq7ymxn2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQTkrRUM4a3FPbUJtU1ZL
            OThkUWtjdE0xVVBYZnRCajlIazI1Y25UVVFrCkZVVEZwZFIxTnVCQkwyRmJubWRO
            YUZ4ZzY5TXo4cFhvVXc0T3Z6K0RqUUUKLS0tIFhxOGVNTkEzbDEvdHp3cDE5Ty9J
            ZGNJbXEyd1FNMzZBSFRqWXVQd01Ua3cKaliyFpfCN9vudzw8CBEgkXdp6Ug2QbIn
            XXaWIjw4H1HRPKbg6LfHoDGwwLZUZlpOgfygGRRwM0uLIgetZcOxSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-14T21:45:26Z"
    mac: ENC[AES256_GCM,data:yNcCG70IYj56bXSYkFR9wYB79Pc7AoH/Qx0PFLH6HDE88Lx9nCHmAxQ3zrQX5ncl12715P/MNhBGKvRNQw9DoaDCAqI4dC4ve9VRguOhfi6V9px+nH081nFPX7R+biAbiIQxD2UiyuBR+GSqA4lz9WbnnbyBMCjHZFRpvuggRDs=,iv:F/hZydwpiL4uSbj1B+QCH6XUHs1G5zAVowgEGFrYDJI=,tag:woPBQFKwjOqt9YzMZaSb4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
