apiVersion: v1
kind: Secret
metadata:
    name: iam
    namespace: default
stringData:
    oauth-client-secret: ENC[AES256_GCM,data:91Jo6rDuGAfMXQwiZ6EC9u7QmMVuSVrz6k72sDd187EI5KP6yKCtQJWwWFTKKaJYLPS0bMDvuh4EkPb5LpHonftwkVrznJxd,iv:1ADvWP4Fp/gZZlLkJEuN1obbghkLr2Xaj3PKMn7LE0I=,tag:90+9mXF2u/ZtV7xRal17Cw==,type:str]
    oauth-client-id: ENC[AES256_GCM,data:Z2z6gMU5GwZoxJqVHALU3bayshFZX/A4hZDD+CSOIfO47vs=,iv:Pruno97mu95pB0dUDGzGEkwm3PWVa+blaQOeZpU221U=,tag:ugzFv9yLI6hu8z4oZgRhEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ug2fepnvaqsfpn7t5gjjh2l0j8074jwh9h50pnjcjxn08v8pp3xq7ymxn2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBS2dKOTlvU0piTkF2bjh1
            VTJxYmJLVmJRUmRnK1RHMU5VY1dpQ2NDaUUwCnRENW9vdDlMOFg4a054ZVRHOUI1
            d3d4TVZjV2d6aG5CZ3FVQktCVDVVSk0KLS0tIEdVeG8vcVhLWlFBdjVvaSs3ZUJH
            Y21vLzZDemluYURicXJPUkg4WGFmeEUKbPAgCT41uXL5HhYlX07T1hEgQhtSrQlu
            3sPDKtY7lNc4/yAZL02PdjbTU0wryQLOgkBMSbRh9k8Fkr9THN1Taw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-14T16:11:33Z"
    mac: ENC[AES256_GCM,data:ygCRATrBpC1P/E9aOlMQ2dm3cXgL0faRhrXpp15CgLZOM9WoFM4cO4SDaJYCgd7wI1cXBOhbnEOXfswjwwNhg18sxZPFuDnKjcFNiUVvdtDtFiMN0Y71peGLu67vDtBujZVrLfVxO+eVk8zn0+rsZLg6GBKrnH5iTZ44ewYjNX4=,iv:KITfuFuSZnRlUYPoZPqyPwBJQ1UmKH3q6p6ibr5YbVc=,tag:qYDSLznXGuFFUEhWmlEBwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
