apiVersion: v1
kind: Secret
metadata:
  name: mand
  namespace: default
data:
  clientSecret: ENC[AES256_GCM,data:NtxRIWP7ZenRDTyteS5JDJ57ZBRD8BBnSr1FJZVhLAEUpCYFxk/9oGTl0AQ9bKzxuztU1ZjqHUetgJsjEirsCWikBVRZy830N6xxLIxDHKmnPDd5nd9XzAncgtFhtHwgJ/lJSCifnkkF0gu2zXmSetHUAAc=,iv:6JVFwGa8q1VZs0f8rgASt0UF9X9ZuP/gbNWwA9+2mxE=,tag:rn7BNPb/fD6E+Tdbu6HpZw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ug2fepnvaqsfpn7t5gjjh2l0j8074jwh9h50pnjcjxn08v8pp3xq7ymxn2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZHhWOFYySmVJRE1ZU2VJ
        VkpVV3FyTDF1bVB6dExBaXZpYVpMdHk0dkFvCnRod3RXbm1JTjdqYTBCMklBenRq
        RGNtQzYwK21EV2M1UUhPMTB0RklVNlEKLS0tIE02YUhFTkN0Qk5QY0x2SUQ4cy9B
        NjQxNzdqVURCTGRtdU5SUng0Wis5RUkKx5L84d0Gdy1J1ehFx/IWK3XkCmB1amr7
        ih3Ffn4fYG4DxTkN8kIm4Aaw2zHqM1lkIsK3etbNUFfPoiu/uxhSqA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2022-12-21T00:59:19Z"
  mac: ENC[AES256_GCM,data:4o9EvdJ+8ZmQ1H9X42gK28i4LT4yYyKIqyxUKOiCK9mFvNLGW8p+quXdRJZGEvMcN0j1P31N849nRBtzbUdgIuVOrOXKQrvsEUPmNcX4lKGEl6N+Nji7lcE8vJpZi3ZqU7DF5gZWyh29aJ+kFkBf0bSSKVGaNpvy0L8D3yOodUM=,iv:aUl/Mgt8hmJEMGDaMZZBjPDMRE/3jdy4Vla+IHVqL+Y=,tag:Y87cvbizJHNKK3ZcdpAx+g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
