apiVersion: v1
kind: Secret
metadata:
    name: passes
    namespace: default
stringData:
    applePassTypeIdentifier: ENC[AES256_GCM,data:ZisoUYPRtmyyYO7+c/v2a74dQoWoSak0YA==,iv:9cTT7yYhs+7DM0yYLMmpW6b51zGxwreFu0qWouQmAUg=,tag:0vvqvED+CNfz7xJYyPPtgQ==,type:str]
    appleTeamIdentifier: ENC[AES256_GCM,data:3KpExSuuLILsbg==,iv:/m+BIRC+lm/2IfV7Z+i0ADjECh0n+yH20VCuZYOLKbQ=,tag:sb/NEClRzTlF5dBW6G7sbw==,type:str]
    certificatePath: ENC[AES256_GCM,data:Hm3E90jJP17bBqf9xOI=,iv:oCdJLPzDo2TkCPNSijaUPwCU9HlY27ilERd2dHN9NYw=,tag:lOzWDCpbusq98mh/i3JtEg==,type:str]
    certificatePassword: ENC[AES256_GCM,data:8lQlidfnG8NUS11/eFBgW2t0+4wTkBU8GfEhs1cd,iv:tQYLCHqLHnhWozI7lVLSQIV/v9l4HpMt3YAfciG7+WE=,tag:AhZkAJhazzpt5/C4U4MHtA==,type:str]
sops:
    age:
        - recipient: age1ug2fepnvaqsfpn7t5gjjh2l0j8074jwh9h50pnjcjxn08v8pp3xq7ymxn2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQi9QemlHeHhsckVPcnNI
            RENpM0xaRDFnS1g1ZFcvM0dzbVlGVGFCOUE0Cm5ScnF4QVhDeFBkVkFhdGI3QVEw
            TjNrUlNtL05uSEtjRDR5K0puaW1BVncKLS0tIGNleWhWU01KQWwyY3JaZW9xQnUr
            emZDdWZOcnJyclh2L3FTSnUyTUthYzgKMcZMEvbsM/tEBH3Q+E70omRRbfHuXF/N
            Mf6a0ZaOGYSSmOaKlLvMZCOXdYYiFh2xh8DRF0Q9H2AmBLGwyDddIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T12:01:20Z"
    mac: ENC[AES256_GCM,data:v9pjenjFoF+QLFYEXL4G4bUxe+30WtyrzrGEfMakXNNv3nWvC5cbozuKlOIGZrcgR3nXAccYHKriF3y6O76G7EslgDix2cRs+fYmpaOG40ovUAnYcqe98r3av2awekGahUodMqTArGsgKZvQKkDgVV1a/tmhHqk1Plvp+aJi0zU=,iv:zIXXKXw0d1ACfHQs5DzVMwY5tNMzBtodVHAbLBz4MV0=,tag:atz5HBCrK2HIMGDV2kuWHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
