apiVersion: v1
kind: Secret
metadata:
    name: passes
    namespace: default
stringData:
    applePassTypeIdentifier: ENC[AES256_GCM,data:+bOeOgeLMPj1tAxlQdoHlUf7EP3alUrv2Q==,iv:9j38bg+JCrMy9jEI5nUp9NJ/WEt7t3jYsw96MYc4ues=,tag:qdD+7IZ67gp3cOxqmbVxLQ==,type:str]
    appleTeamIdentifier: ENC[AES256_GCM,data:dijBdkYbTl+pmg==,iv:I601bXJtrUL8zuroUcBvQOyfnqzbkyHOZU3sNgfLtiQ=,tag:MXnoar4WksCS0I+MuuKjdQ==,type:str]
    certificatePath: ENC[AES256_GCM,data:lVRVchoPqrNj/5sOmqU=,iv:0U5svSNFGCSQz6zXhs/j6qUOxhVj7IBn+slSrFcaXB4=,tag:j4xRKegWpxruF7sbzcD8Ew==,type:str]
    certificatePassword: ENC[AES256_GCM,data:EFUZTRu2J95zQSOd2MY+l2M0V2MlP3pzZ8r49Blx,iv:kCG7mifi+iZv9XuYEVkRSudgJ2lYt+fjRP6a4Spfs08=,tag:EEePzpBrTVIXtU4I6UX/bw==,type:str]
sops:
    age:
        - recipient: age1ug2fepnvaqsfpn7t5gjjh2l0j8074jwh9h50pnjcjxn08v8pp3xq7ymxn2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkV21sY2g4V2M0dWhQSklR
            ZmV4anA0MStQYzlqNlZ0Q3lkUHJoYmd6VnhRCmlQbC94R3V1cHQ4cytDTm9WMUtP
            UVJZR2hUUU80NXNLNkkzVkhreUxCUkEKLS0tIFBZQTB4VllIR1Z3TnhXb0NIRkI4
            cXhTMllJQmlFSHJQcTNCWnduU05HMnMKIy2/0O+O92/DIoeNLe8wm5quxznzUi7M
            1IZFHGcrrpgvdHf1X0gjogwmGQ3vT9Rjbz3bdsBPSy+qwci39Ws3zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T12:31:52Z"
    mac: ENC[AES256_GCM,data:fA8EQCbETeQpXFS7muNzR8sOXnQQkU2hCF2krPK0Yz2yl16vnRZP+Sgl5MKYCVN+iruu5vV2lt7Jh4ZmfVDt9G0J8/EBN/g7O32iY7c3lS/0+o+iYMUb04C2UdrDaFbTMqlIHEFFv3v7KKWHHHYiSRlElyY59oqc/LyuXY229h8=,iv:9N+7hrPvKuUh5wch+Vs4KTm1EYI7/ET78/ED+VB8gPk=,tag:czooHN4/+noBgbvblKTnlA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
