apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.3.x"
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      watchIngressWithoutClass: true
      enableLatencyMetrics: true
      service:
        ipFamilyPolicy: "PreferDualStack"
        ipFamilies:
          - IPv4
          - IPv6
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/port: "10254"
            prometheus.io/scrape: "true"
      ingressClassResource:
        default: true
      admissionWebhooks:
        enabled: false
      extraArgs:
        default-ssl-certificate: "default/wisvch-tls"
    prometheus:
      create: true
