apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: archive
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./archive
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    fullnameOverride: archive
    ingress:
      tudelft:
        domains:
          - coh.ewi.tudelft.nl
          - icpc.tudelft.nl
    domains:
      - alumni.ch.tudelft.nl
      - commissies.ch.tudelft.nl
      - eerstejaarsweekend.nl
      - lustrum.ch
      - symposium.ch.tudelft.nl
    replicaCount: 1
    containerPort: 8080
    service:
      type: ClusterIP
      port: 80
    image:
      repository: ghcr.io/wisvch/archived-static
      tag: 20250107-de4fefd # {"$imagepolicy": "flux-system:archived-static:tag"}
      pullPolicy: IfNotPresent
      pullSecrets: {}
  resources: # typical usage cpu: 0.00026, mem: 36MiB
    limits:
      cpu: 2m
      memory: 128Mi
    requests:
      cpu: 1m
      memory: 64Mi
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: archive
  namespace: default
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        host: lustrum.ch
        requestPath: /
    logConfig:
      enabled: true
  targetRef:
    group: ""
    kind: Service
    name: archive
