apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: archive
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./archive
      version: "0.1.x"
      interval: 15m
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: wisvch
        namespace: flux-system
  values:
    fullnameOverride: archive
    ingress:
      tudelft:
        domains:
          - coh.ewi.tudelft.nl
          - icpc.tudelft.nl
    domains:
      - alumni.ch.tudelft.nl
      - commissies.ch.tudelft.nl
      - eerstejaarsweekend.nl
      - lustrum.ch
      - symposium.ch.tudelft.nl
      - hackdelft.nl
      - hackdelft.com
      - 2022.hackdelft.nl
      - 2022.hackdelft.com
      - 2019.hackdelft.nl
      - 2019.hackdelft.com
      - 2018.hackdelft.nl
      - 2018.hackdelft.com
      - 2017.hackdelft.nl
      - 2017.hackdelft.com
      - 2022.nwerc.eu
      - 2023.nwerc.eu
      - 2024.nwerc.eu
      - businesstour.ch.tudelft.nl
      - businesstour.wisv.ch
      - 2001.bapc.eu
      - 2002.nwerc.eu
      - 2005.bapc.eu
      - 2008.bapc.eu
      - 2012.nwerc.eu
      - 2013.nwerc.eu
      - 2016.bapc.eu
      - 2020.bapc.eu
    replicaCount: 1
    containerPort: 8080
    service:
      type: ClusterIP
      port: 80
    image:
      repository: ghcr.io/wisvch/archived-static
      tag: 20250921-92ee3d4 # {"$imagepolicy": "flux-system:archived-static:tag"}
      pullPolicy: IfNotPresent
      pullSecrets: {}
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: archive
  namespace: default
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        host: lustrum.ch
        requestPath: /
    logConfig:
      enabled: true
  targetRef:
    group: ""
    kind: Service
    name: archive
